#############################################################################
# Makefile for building: SLAMNAV
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  SLAMNAV.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile SLAMNAV.pro -spec linux-g++ CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DVERSION_LOG=\"1.7.5\" -DBUILD_DATE="\"$(shell date +"%Y-%m-%d %H:%M:%S")\"" -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -fopenmp -O3 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -fopenmp -O3 -std=gnu++1y -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I../../rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I../../OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SLAMNAV1.0.0
DISTDIR = /home/rainbow/code/SLAMNAV_order/.tmp/SLAMNAV1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/lib/x86_64-linux-gnu/ -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_objdetect -lopencv_photo -lopencv_video -lopencv_videoio -lopencv_ximgproc -lboost_system -lboost_thread -ltbb -lgomp -L/home/rainbow/rplidar_sdk/output/Linux/Release/ -lsl_lidar_sdk -L/usr/local/lib/ -lsick_safetyscanners_base -L/home/rainbow/OrbbecSDK/build/install/lib/ -lOrbbecSDK /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5WebSockets.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = LakiBeamHTTP.cpp \
		LakiBeamUDP.cpp \
		Logger.cpp \
		autocontrol.cpp \
		cam.cpp \
		cmd_server.cpp \
		cv_to_qt.cpp \
		integrate_ui.cpp \
		ipc.cpp \
		l2c.cpp \
		lidar_2d.cpp \
		main.cpp \
		mainwindow.cpp \
		mobile.cpp \
		multicontrol.cpp \
		mygraphicsview.cpp \
		p2o.cpp \
		sim.cpp \
		slam_2d.cpp \
		submap.cpp \
		topomap.cpp \
		unimap.cpp \
		ws_client.cpp qrc_img.cpp \
		moc_Logger.cpp \
		moc_autocontrol.cpp \
		moc_cam.cpp \
		moc_cmd_server.cpp \
		moc_integrate_ui.cpp \
		moc_ipc.cpp \
		moc_l2c.cpp \
		moc_lidar_2d.cpp \
		moc_mainwindow.cpp \
		moc_mobile.cpp \
		moc_multicontrol.cpp \
		moc_mygraphicsview.cpp \
		moc_sim.cpp \
		moc_slam_2d.cpp \
		moc_submap.cpp \
		moc_topomap.cpp \
		moc_unimap.cpp \
		moc_ws_client.cpp
OBJECTS       = LakiBeamHTTP.o \
		LakiBeamUDP.o \
		Logger.o \
		autocontrol.o \
		cam.o \
		cmd_server.o \
		cv_to_qt.o \
		integrate_ui.o \
		ipc.o \
		l2c.o \
		lidar_2d.o \
		main.o \
		mainwindow.o \
		mobile.o \
		multicontrol.o \
		mygraphicsview.o \
		p2o.o \
		sim.o \
		slam_2d.o \
		submap.o \
		topomap.o \
		unimap.o \
		ws_client.o \
		qrc_img.o \
		moc_Logger.o \
		moc_autocontrol.o \
		moc_cam.o \
		moc_cmd_server.o \
		moc_integrate_ui.o \
		moc_ipc.o \
		moc_l2c.o \
		moc_lidar_2d.o \
		moc_mainwindow.o \
		moc_mobile.o \
		moc_multicontrol.o \
		moc_mygraphicsview.o \
		moc_sim.o \
		moc_slam_2d.o \
		moc_submap.o \
		moc_topomap.o \
		moc_unimap.o \
		moc_ws_client.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qtquickcompiler.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SLAMNAV.pro LakiBeamHTTP.h \
		LakiBeamUDP.h \
		Logger.h \
		autocontrol.h \
		cam.h \
		cmd_server.h \
		cv_to_qt.h \
		global_defines.h \
		integrate_ui.h \
		ipc.h \
		l2c.h \
		lidar_2d.h \
		mainwindow.h \
		mobile.h \
		multicontrol.h \
		mygraphicsview.h \
		nanoflann.hpp \
		p2o.h \
		sim.h \
		slam_2d.h \
		spline.h \
		submap.h \
		topomap.h \
		unimap.h \
		ws_client.h LakiBeamHTTP.cpp \
		LakiBeamUDP.cpp \
		Logger.cpp \
		autocontrol.cpp \
		cam.cpp \
		cmd_server.cpp \
		cv_to_qt.cpp \
		integrate_ui.cpp \
		ipc.cpp \
		l2c.cpp \
		lidar_2d.cpp \
		main.cpp \
		mainwindow.cpp \
		mobile.cpp \
		multicontrol.cpp \
		mygraphicsview.cpp \
		p2o.cpp \
		sim.cpp \
		slam_2d.cpp \
		submap.cpp \
		topomap.cpp \
		unimap.cpp \
		ws_client.cpp
QMAKE_TARGET  = SLAMNAV
DESTDIR       = 
TARGET        = SLAMNAV


first: all
####### Build rules

SLAMNAV: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SLAMNAV.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qtquickcompiler.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SLAMNAV.pro \
		img.qrc
	$(QMAKE) -o Makefile SLAMNAV.pro -spec linux-g++ CONFIG+=qtquickcompiler
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qtquickcompiler.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
SLAMNAV.pro:
img.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile SLAMNAV.pro -spec linux-g++ CONFIG+=qtquickcompiler

qmake_all: FORCE


all: Makefile SLAMNAV

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents img.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents LakiBeamHTTP.h LakiBeamUDP.h Logger.h autocontrol.h cam.h cmd_server.h cv_to_qt.h global_defines.h integrate_ui.h ipc.h l2c.h lidar_2d.h mainwindow.h mobile.h multicontrol.h mygraphicsview.h nanoflann.hpp p2o.h sim.h slam_2d.h spline.h submap.h topomap.h unimap.h ws_client.h $(DISTDIR)/
	$(COPY_FILE) --parents LakiBeamHTTP.cpp LakiBeamUDP.cpp Logger.cpp autocontrol.cpp cam.cpp cmd_server.cpp cv_to_qt.cpp integrate_ui.cpp ipc.cpp l2c.cpp lidar_2d.cpp main.cpp mainwindow.cpp mobile.cpp multicontrol.cpp mygraphicsview.cpp p2o.cpp sim.cpp slam_2d.cpp submap.cpp topomap.cpp unimap.cpp ws_client.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_img.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_img.cpp
qrc_img.cpp: img.qrc \
		/usr/lib/qt5/bin/rcc \
		resource/Pin_Map_Vector.png
	/usr/lib/qt5/bin/rcc -name img img.qrc -o qrc_img.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -fopenmp -O3 -std=gnu++1y -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Logger.cpp moc_autocontrol.cpp moc_cam.cpp moc_cmd_server.cpp moc_integrate_ui.cpp moc_ipc.cpp moc_l2c.cpp moc_lidar_2d.cpp moc_mainwindow.cpp moc_mobile.cpp moc_multicontrol.cpp moc_mygraphicsview.cpp moc_sim.cpp moc_slam_2d.cpp moc_submap.cpp moc_topomap.cpp moc_unimap.cpp moc_ws_client.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Logger.cpp moc_autocontrol.cpp moc_cam.cpp moc_cmd_server.cpp moc_integrate_ui.cpp moc_ipc.cpp moc_l2c.cpp moc_lidar_2d.cpp moc_mainwindow.cpp moc_mobile.cpp moc_multicontrol.cpp moc_mygraphicsview.cpp moc_sim.cpp moc_slam_2d.cpp moc_submap.cpp moc_topomap.cpp moc_unimap.cpp moc_ws_client.cpp
moc_Logger.cpp: Logger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Logger.h -o moc_Logger.cpp

moc_autocontrol.cpp: autocontrol.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		mobile.h \
		l2c.h \
		slam_2d.h \
		p2o.h \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		submap.h \
		unimap.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp \
		spline.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include autocontrol.h -o moc_autocontrol.cpp

moc_cam.cpp: cam.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include cam.h -o moc_cam.cpp

moc_cmd_server.cpp: cmd_server.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include cmd_server.h -o moc_cmd_server.cpp

moc_integrate_ui.cpp: integrate_ui.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		autocontrol.h \
		mobile.h \
		l2c.h \
		slam_2d.h \
		p2o.h \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		submap.h \
		unimap.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp \
		spline.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include integrate_ui.h -o moc_integrate_ui.cpp

moc_ipc.cpp: ipc.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ipc.h -o moc_ipc.cpp

moc_l2c.cpp: l2c.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include l2c.h -o moc_l2c.cpp

moc_lidar_2d.cpp: lidar_2d.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		mobile.h \
		l2c.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lidar_2d.h -o moc_lidar_2d.cpp

moc_mainwindow.cpp: mainwindow.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		ipc.h \
		unimap.h \
		submap.h \
		topomap.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		mobile.h \
		l2c.h \
		slam_2d.h \
		p2o.h \
		autocontrol.h \
		spline.h \
		multicontrol.h \
		ws_client.h \
		cmd_server.h \
		integrate_ui.h \
		sim.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_mobile.cpp: mobile.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		l2c.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mobile.h -o moc_mobile.cpp

moc_multicontrol.cpp: multicontrol.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		mobile.h \
		l2c.h \
		slam_2d.h \
		p2o.h \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		submap.h \
		unimap.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp \
		ws_client.h \
		spline.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include multicontrol.h -o moc_multicontrol.cpp

moc_mygraphicsview.cpp: mygraphicsview.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mygraphicsview.h -o moc_mygraphicsview.cpp

moc_sim.cpp: sim.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		mobile.h \
		l2c.h \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include sim.h -o moc_sim.cpp

moc_slam_2d.cpp: slam_2d.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		p2o.h \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		mobile.h \
		l2c.h \
		submap.h \
		unimap.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include slam_2d.h -o moc_slam_2d.cpp

moc_submap.cpp: submap.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include submap.h -o moc_submap.cpp

moc_topomap.cpp: topomap.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		unimap.h \
		submap.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include topomap.h -o moc_topomap.cpp

moc_unimap.cpp: unimap.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		submap.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include unimap.h -o moc_unimap.cpp

moc_ws_client.cpp: ws_client.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/rainbow/code/SLAMNAV_order/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/rainbow/code/SLAMNAV_order -I/usr/include/opencv4 -I/usr/include/rapidjson -I/usr/include/boost -I/usr/include/boost/beast -I/usr/include/eigen3 -I/usr/local/include/sophus -I/home/rainbow/rplidar_sdk/sdk/include -I/usr/local/include/sick_safetyscanners_base -I/home/rainbow/OrbbecSDK/build/install/include -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ws_client.h -o moc_ws_client.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic \
		mygraphicsview.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

LakiBeamHTTP.o: LakiBeamHTTP.cpp LakiBeamHTTP.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LakiBeamHTTP.o LakiBeamHTTP.cpp

LakiBeamUDP.o: LakiBeamUDP.cpp LakiBeamUDP.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LakiBeamUDP.o LakiBeamUDP.cpp

Logger.o: Logger.cpp Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Logger.o Logger.cpp

autocontrol.o: autocontrol.cpp autocontrol.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		mobile.h \
		l2c.h \
		slam_2d.h \
		p2o.h \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		submap.h \
		unimap.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp \
		spline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autocontrol.o autocontrol.cpp

cam.o: cam.cpp cam.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cam.o cam.cpp

cmd_server.o: cmd_server.cpp cmd_server.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmd_server.o cmd_server.cpp

cv_to_qt.o: cv_to_qt.cpp cv_to_qt.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cv_to_qt.o cv_to_qt.cpp

integrate_ui.o: integrate_ui.cpp integrate_ui.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		autocontrol.h \
		mobile.h \
		l2c.h \
		slam_2d.h \
		p2o.h \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		submap.h \
		unimap.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp \
		spline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o integrate_ui.o integrate_ui.cpp

ipc.o: ipc.cpp ipc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ipc.o ipc.cpp

l2c.o: l2c.cpp l2c.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o l2c.o l2c.cpp

lidar_2d.o: lidar_2d.cpp lidar_2d.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		mobile.h \
		l2c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lidar_2d.o lidar_2d.cpp

main.o: main.cpp mainwindow.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		ipc.h \
		unimap.h \
		submap.h \
		topomap.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		mobile.h \
		l2c.h \
		slam_2d.h \
		p2o.h \
		autocontrol.h \
		spline.h \
		multicontrol.h \
		ws_client.h \
		cmd_server.h \
		integrate_ui.h \
		sim.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		ipc.h \
		unimap.h \
		submap.h \
		topomap.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		mobile.h \
		l2c.h \
		slam_2d.h \
		p2o.h \
		autocontrol.h \
		spline.h \
		multicontrol.h \
		ws_client.h \
		cmd_server.h \
		integrate_ui.h \
		sim.h \
		ui_mainwindow.h \
		mygraphicsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mobile.o: mobile.cpp mobile.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		l2c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mobile.o mobile.cpp

multicontrol.o: multicontrol.cpp multicontrol.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		mobile.h \
		l2c.h \
		slam_2d.h \
		p2o.h \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		submap.h \
		unimap.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp \
		ws_client.h \
		spline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multicontrol.o multicontrol.cpp

mygraphicsview.o: mygraphicsview.cpp mygraphicsview.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mygraphicsview.o mygraphicsview.cpp

p2o.o: p2o.cpp p2o.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o p2o.o p2o.cpp

sim.o: sim.cpp sim.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		mobile.h \
		l2c.h \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sim.o sim.cpp

slam_2d.o: slam_2d.cpp slam_2d.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		p2o.h \
		lidar_2d.h \
		../../rplidar_sdk/sdk/include/sl_lidar.h \
		../../rplidar_sdk/sdk/include/sl_lidar_driver.h \
		../../rplidar_sdk/sdk/include/sl_lidar_cmd.h \
		../../rplidar_sdk/sdk/include/sl_lidar_protocol.h \
		../../rplidar_sdk/sdk/include/sl_types.h \
		LakiBeamHTTP.h \
		LakiBeamUDP.h \
		mobile.h \
		l2c.h \
		submap.h \
		unimap.h \
		cam.h \
		../../OrbbecSDK/build/install/include/libobsensor/ObSensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Context.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Types.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/ObTypes.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Device.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/h/Property.h \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Filter.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Error.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Frame.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Pipeline.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/RecordPlayback.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Sensor.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/StreamProfile.hpp \
		../../OrbbecSDK/build/install/include/libobsensor/hpp/Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o slam_2d.o slam_2d.cpp

submap.o: submap.cpp submap.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o submap.o submap.cpp

topomap.o: topomap.cpp topomap.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		unimap.h \
		submap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o topomap.o topomap.cpp

unimap.o: unimap.cpp unimap.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h \
		submap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o unimap.o unimap.cpp

ws_client.o: ws_client.cpp ws_client.h \
		global_defines.h \
		cv_to_qt.h \
		nanoflann.hpp \
		Logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ws_client.o ws_client.cpp

qrc_img.o: qrc_img.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_img.o qrc_img.cpp

moc_Logger.o: moc_Logger.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Logger.o moc_Logger.cpp

moc_autocontrol.o: moc_autocontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_autocontrol.o moc_autocontrol.cpp

moc_cam.o: moc_cam.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cam.o moc_cam.cpp

moc_cmd_server.o: moc_cmd_server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmd_server.o moc_cmd_server.cpp

moc_integrate_ui.o: moc_integrate_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_integrate_ui.o moc_integrate_ui.cpp

moc_ipc.o: moc_ipc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ipc.o moc_ipc.cpp

moc_l2c.o: moc_l2c.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_l2c.o moc_l2c.cpp

moc_lidar_2d.o: moc_lidar_2d.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lidar_2d.o moc_lidar_2d.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_mobile.o: moc_mobile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mobile.o moc_mobile.cpp

moc_multicontrol.o: moc_multicontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_multicontrol.o moc_multicontrol.cpp

moc_mygraphicsview.o: moc_mygraphicsview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mygraphicsview.o moc_mygraphicsview.cpp

moc_sim.o: moc_sim.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sim.o moc_sim.cpp

moc_slam_2d.o: moc_slam_2d.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_slam_2d.o moc_slam_2d.cpp

moc_submap.o: moc_submap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_submap.o moc_submap.cpp

moc_topomap.o: moc_topomap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_topomap.o moc_topomap.cpp

moc_unimap.o: moc_unimap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_unimap.o moc_unimap.cpp

moc_ws_client.o: moc_ws_client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ws_client.o moc_ws_client.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/SLAMNAV/bin || mkdir -p $(INSTALL_ROOT)/opt/SLAMNAV/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/SLAMNAV/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/SLAMNAV/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/SLAMNAV/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/SLAMNAV/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

